apiVersion: v1
kind: Service
metadata:
  labels:
    service: app
  name: app
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
      nodePort: 32000
    - name: "3306"
      port: 3306
      targetPort: 3306
      nodePort: 31000
  type: NodePort
  selector:
    service: app
