# Use root/example as user/password credentials
version: '3.9'

services:

  db:
    build:
      context: ./db
      network: host
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - my_volume:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: qwerty
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: db_name
      MYSQL_USER: not_root

    ports:
      - "3306:3306"
    

  app:
    build:
      context: ./app
      network: host
    restart: always
    environment:
      MYSQL_HOST: db
    
    ports:
      - "5000:5000"
    links:
      - db

volumes:
  my_volume:
